version: '3'

services:
  postgres:
    image: postgres:15.5
    environment:
      POSTGRES_USER: sqladmin
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"  # Map the PostgreSQL port to the host machine
