server:
  port: 8088

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/clinic
    username: postgres
    password: 123456

  jpa:
    properties:
      hibernate:
        jdbc:
          time_zone: UTC